---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: javawebapp
  name: java-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - image: 007892345/testapp:BUILD_NUMBER
        name: javawebapp
        imagePullPolicy: Always
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: javawebapp
  name: javawebapp
spec:
  selector:
    app: javawebapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp
